// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calculator.proto

#include "calculator.pb.h"
#include "calculator.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ProtocolServiceTest_method_names[] = {
  "/ProtocolServiceTest/Add",
  "/ProtocolServiceTest/Sub",
  "/ProtocolServiceTest/Mul",
  "/ProtocolServiceTest/Div",
};

std::unique_ptr< ProtocolServiceTest::Stub> ProtocolServiceTest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProtocolServiceTest::Stub> stub(new ProtocolServiceTest::Stub(channel, options));
  return stub;
}

ProtocolServiceTest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Add_(ProtocolServiceTest_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sub_(ProtocolServiceTest_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Mul_(ProtocolServiceTest_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Div_(ProtocolServiceTest_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ProtocolServiceTest::Stub::Add(::grpc::ClientContext* context, const ::operands2& request, ::result1* response) {
  return ::grpc::internal::BlockingUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void ProtocolServiceTest::Stub::async::Add(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void ProtocolServiceTest::Stub::async::Add(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::result1, ::operands2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtocolServiceTest::Stub::Sub(::grpc::ClientContext* context, const ::operands2& request, ::result1* response) {
  return ::grpc::internal::BlockingUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sub_, context, request, response);
}

void ProtocolServiceTest::Stub::async::Sub(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sub_, context, request, response, std::move(f));
}

void ProtocolServiceTest::Stub::async::Sub(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sub_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::PrepareAsyncSubRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::result1, ::operands2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sub_, context, request);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::AsyncSubRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtocolServiceTest::Stub::Mul(::grpc::ClientContext* context, const ::operands2& request, ::result1* response) {
  return ::grpc::internal::BlockingUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Mul_, context, request, response);
}

void ProtocolServiceTest::Stub::async::Mul(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mul_, context, request, response, std::move(f));
}

void ProtocolServiceTest::Stub::async::Mul(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mul_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::PrepareAsyncMulRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::result1, ::operands2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Mul_, context, request);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::AsyncMulRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMulRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtocolServiceTest::Stub::Div(::grpc::ClientContext* context, const ::operands2& request, ::result1* response) {
  return ::grpc::internal::BlockingUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Div_, context, request, response);
}

void ProtocolServiceTest::Stub::async::Div(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Div_, context, request, response, std::move(f));
}

void ProtocolServiceTest::Stub::async::Div(::grpc::ClientContext* context, const ::operands2* request, ::result1* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Div_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::PrepareAsyncDivRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::result1, ::operands2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Div_, context, request);
}

::grpc::ClientAsyncResponseReader< ::result1>* ProtocolServiceTest::Stub::AsyncDivRaw(::grpc::ClientContext* context, const ::operands2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDivRaw(context, request, cq);
  result->StartCall();
  return result;
}

ProtocolServiceTest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtocolServiceTest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtocolServiceTest::Service, ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtocolServiceTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::operands2* req,
             ::result1* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtocolServiceTest_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtocolServiceTest::Service, ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtocolServiceTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::operands2* req,
             ::result1* resp) {
               return service->Sub(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtocolServiceTest_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtocolServiceTest::Service, ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtocolServiceTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::operands2* req,
             ::result1* resp) {
               return service->Mul(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtocolServiceTest_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtocolServiceTest::Service, ::operands2, ::result1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtocolServiceTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::operands2* req,
             ::result1* resp) {
               return service->Div(ctx, req, resp);
             }, this)));
}

ProtocolServiceTest::Service::~Service() {
}

::grpc::Status ProtocolServiceTest::Service::Add(::grpc::ServerContext* context, const ::operands2* request, ::result1* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtocolServiceTest::Service::Sub(::grpc::ServerContext* context, const ::operands2* request, ::result1* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtocolServiceTest::Service::Mul(::grpc::ServerContext* context, const ::operands2* request, ::result1* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtocolServiceTest::Service::Div(::grpc::ServerContext* context, const ::operands2* request, ::result1* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


